# Generated by Django 5.2.1 on 2025-06-03 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/categories/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='جمع اولیه')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مجموع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('name_en', models.CharField(max_length=200, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت تخفیف\u200cدار')),
                ('image', models.ImageField(upload_to='shop/products/', verbose_name='تصویر اصلی')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی')),
                ('available_sizes', models.CharField(blank=True, max_length=100, verbose_name='سایزهای موجود')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='جنس')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='رنگ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gym_shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name='سایز')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت واحد')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gym_shop.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/products/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='متن جایگزین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='gym_shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name='سایز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gym_shop.cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
                'unique_together': {('cart', 'product', 'size')},
            },
        ),
    ]
