# Generated by Django 4.2.16 on 2025-07-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('report_period', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=20, verbose_name='دوره گزارش')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='تعداد سفارشات')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل درآمد')),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل سود')),
                ('total_products_sold', models.PositiveIntegerField(default=0, verbose_name='تعداد محصولات فروخته شده')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='مشتریان جدید')),
                ('returning_customers', models.PositiveIntegerField(default=0, verbose_name='مشتریان برگشتی')),
                ('pending_orders', models.PositiveIntegerField(default=0, verbose_name='سفارشات در انتظار')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='سفارشات تکمیل شده')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='سفارشات لغو شده')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='گزارش خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('best_selling_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_selling_reports', to='gym_shop.product', verbose_name='پرفروش\u200cترین محصول')),
            ],
            options={
                'verbose_name': 'گزارش فروش',
                'verbose_name_plural': 'گزارشات فروش',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درآمد')),
                ('income_type', models.CharField(choices=[('product_sale', 'فروش محصول'), ('shipping_fee', 'هزینه ارسال'), ('other', 'سایر درآمدها')], max_length=20, verbose_name='نوع درآمد')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='confirmed', max_length=20, verbose_name='وضعیت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='gym_shop.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'درآمد فروشگاه',
                'verbose_name_plural': 'درآمدهای فروشگاه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShopExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هزینه')),
                ('expense_type', models.CharField(choices=[('product_purchase', 'خرید محصول'), ('shipping_cost', 'هزینه ارسال'), ('marketing', 'تبلیغات'), ('rent', 'اجاره'), ('salary', 'حقوق'), ('utilities', 'آب، برق، گاز'), ('maintenance', 'نگهداری'), ('packaging', 'بسته\u200cبندی'), ('website', 'وب\u200cسایت'), ('other', 'سایر هزینه\u200cها')], max_length=20, verbose_name='نوع هزینه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='shop/receipts/', verbose_name='فایل رسید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='gym_shop.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'هزینه فروشگاه',
                'verbose_name_plural': 'هزینه\u200cهای فروشگاه',
                'ordering': ['-date'],
            },
        ),
    ]
