# Generated by Django 5.2.1 on 2025-08-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_shop', '0003_usershippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cod', 'پرداخت در محل'), ('transfer', 'انتقال بانکی')], default='online', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری'),
        ),
    ]
