# Generated by Django 5.2.1 on 2025-08-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_shop', '0004_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مالیات (12%)'),
        ),
    ]
