# Generated by Django 5.2.1 on 2025-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_shop', '0005_order_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'مشکی'), ('white', 'سفید'), ('red', 'قرمز'), ('blue', 'آبی'), ('navy', 'سرمه\u200cای'), ('green', 'سبز'), ('gray', 'خاکستری'), ('dark_gray', 'خاکستری تیره'), ('light_gray', 'خاکستری روشن'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('brown', 'قهوه\u200cای'), ('beige', 'کرم'), ('maroon', 'زرشکی'), ('olive', 'زیتونی'), ('teal', 'سبز دریایی'), ('lime', 'سبز لیمویی'), ('cyan', 'فیروزه\u200cای'), ('magenta', 'ارغوانی'), ('gold', 'طلایی'), ('silver', 'نقره\u200cای'), ('multicolor', 'رنگارنگ'), ('other', 'سایر')], max_length=50, verbose_name='رنگ'),
        ),
    ]
