# Generated by Django 5.2.1 on 2025-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_shop', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نرخ تبدیل (تومان به دلار)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source', models.CharField(default='Manual', max_length=100, verbose_name='منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نرخ تبدیل ارز',
                'verbose_name_plural': 'نرخ\u200cهای تبدیل ارز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='discount_dollar_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='قیمت تخفیف\u200cدار (دلار)'),
        ),
        migrations.AddField(
            model_name='product',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='قیمت (دلار)'),
        ),
    ]
