# Generated by Django 5.2.1 on 2025-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20250528_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'مدرک', 'verbose_name_plural': 'مدارک'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ\u200cهای تیکت'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='new', max_length=20),
        ),
    ]
