# Generated by Django 5.2.1 on 2025-05-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_alter_document_options_alter_payment_options_and_more'),
        ('gym', '0016_alter_dietplan_options_alter_document_options_and_more'),
    ]

    operations = [
    ]
