# Generated by Django 5.2.1 on 2025-05-31 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_alter_dietplan_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_date'], 'verbose_name': 'سند', 'verbose_name_plural': 'اسناد'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت پشتیبانی', 'verbose_name_plural': 'تیکت\u200cهای پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ\u200cهای تیکت'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_image',
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('membership', 'حق عضویت'), ('workout_plan', 'برنامه تمرینی'), ('diet_plan', 'برنامه غذایی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='تصویر رسید پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته')], default='open', max_length=15, verbose_name='وضعیت'),
        ),
    ]
