# Generated by Django 5.2.1 on 2025-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_alter_document_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='melli_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
