# Generated by Django 5.2.1 on 2025-06-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_alter_userprofile_melli_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyInformationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('height_cm', models.PositiveIntegerField(verbose_name='قد (سانتی متر)')),
                ('weight_kg', models.PositiveIntegerField(verbose_name='وزن (کیلوگرم)')),
                ('disease_history', models.CharField(choices=[('yes', 'دارم'), ('no', 'ندارم')], max_length=3, verbose_name='سابقه بیماری')),
                ('disease_description', models.TextField(blank=True, null=True, verbose_name='توضیحات بیماری')),
                ('body_image_front', models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از جلو')),
                ('body_image_back', models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از پشت')),
                ('body_image_left', models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از سمت چپ')),
                ('body_image_right', models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از سمت راست')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_information', to='gym.userprofile')),
            ],
            options={
                'verbose_name': 'اطلاعات بدنی کاربر',
                'verbose_name_plural': 'اطلاعات بدنی کاربران',
            },
        ),
    ]
