# Generated by Django 5.2.1 on 2025-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_bodyinformationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='نام صاحب کارت')),
                ('price_workout', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت برنامه تمرینی (تومان)')),
                ('price_diet', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت برنامه غذایی (تومان)')),
                ('price_both', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت هر دو برنامه (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'کارت پرداخت',
                'verbose_name_plural': 'کارت\u200cهای پرداخت',
            },
        ),
        migrations.AddField(
            model_name='bodyinformationuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyinformationuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodyinformationuser',
            name='body_image_left',
            field=models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از طرف چپ'),
        ),
        migrations.AlterField(
            model_name='bodyinformationuser',
            name='body_image_right',
            field=models.ImageField(blank=True, null=True, upload_to='body_images/', verbose_name='عکس از طرف راست'),
        ),
        migrations.AlterField(
            model_name='bodyinformationuser',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='وزن (کیلوگرم)'),
        ),
    ]
