# Generated by Django 5.2.1 on 2025-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_paymentcard_bodyinformationuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diet_plans/images/', verbose_name='تصویر برنامه'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_plans/images/', verbose_name='تصویر برنامه'),
        ),
    ]
