# Generated by Django 4.2.16 on 2025-07-10 20:15

from django.db import migrations


def create_default_payment_card(apps, schema_editor):
    """Create a default payment card for the gym"""
    PaymentCard = apps.get_model('gym', 'PaymentCard')
    
    # Check if any payment card already exists
    if not PaymentCard.objects.exists():
        PaymentCard.objects.create(
            card_number='1234567890123456',
            card_holder_name='پلتفرم جامع ورزشی',
            price_workout=500000,  # 500,000 تومان
            price_diet=300000,     # 300,000 تومان
            price_both=700000,     # 700,000 تومان
            is_active=True
        )


def reverse_default_payment_card(apps, schema_editor):
    """Remove default payment card"""
    PaymentCard = apps.get_model('gym', 'PaymentCard')
    PaymentCard.objects.filter(
        card_number='1234567890123456',
        card_holder_name='پلتفرم جامع ورزشی'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_dietplan_image_workoutplan_image'),
    ]

    operations = [
        migrations.RunPython(create_default_payment_card, reverse_default_payment_card),
    ]
