# Generated by Django 4.2.16 on 2025-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_auto_20250710_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='target_body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='هدف درصد چربی بدن (%)'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='target_muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='هدف توده عضلانی (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='هدف وزن (کیلوگرم)'),
        ),
    ]
