# Generated by Django 4.2.16 on 2025-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_monthlygoal_target_body_fat_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان هدف'),
        ),
    ]
