# Generated by Django 4.2.16 on 2025-07-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0025_alter_monthlygoal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('file', models.FileField(upload_to='booklets/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'جزوه',
                'verbose_name_plural': 'جزوات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.CreateModel(
            name='BookletPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('proof_image', models.ImageField(upload_to='booklet_payment_proofs/', verbose_name='تصویر رسید پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym.booklet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرداخت جزوه',
                'verbose_name_plural': 'پرداخت\u200cهای جزوه',
                'ordering': ['-payment_date'],
            },
        ),
    ]
