# Generated by Django 4.2.16 on 2025-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_booklet_payment_card_number_bookletpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='body_fat_goal_direction',
            field=models.CharField(blank=True, choices=[('lose', 'کاهش'), ('gain', 'افزایش'), ('maintain', 'حفظ')], max_length=10, null=True, verbose_name='جهت هدف چربی'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='muscle_mass_goal_direction',
            field=models.CharField(blank=True, choices=[('lose', 'کاهش'), ('gain', 'افزایش'), ('maintain', 'حفظ')], max_length=10, null=True, verbose_name='جهت هدف عضله'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='weight_goal_direction',
            field=models.CharField(blank=True, choices=[('lose', 'کاهش'), ('gain', 'افزایش'), ('maintain', 'حفظ')], max_length=10, null=True, verbose_name='جهت هدف وزن'),
        ),
    ]
