# Generated by Django 4.2.16 on 2025-07-12 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0028_userprofile_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(max_length=254, verbose_name='ایمیل دریافت اطلاع\u200cرسانی')),
                ('notify_shop_orders', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی سفارشات فروشگاه')),
                ('notify_shop_order_status_change', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی تغییر وضعیت سفارش')),
                ('notify_workout_plan_requests', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی درخواست برنامه تمرینی')),
                ('notify_diet_plan_requests', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی درخواست برنامه غذایی')),
                ('notify_new_user_registration', models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی کاربران جدید')),
                ('notify_payment_uploads', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی آپلود رسید پرداخت')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'بلافاصله'), ('hourly', 'هر ساعت'), ('daily', 'روزانه'), ('weekly', 'هفتگی')], default='immediate', max_length=20, verbose_name='فرکانس اطلاع\u200cرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('admin_user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ادمین')),
            ],
            options={
                'verbose_name': 'تنظیمات اطلاع\u200cرسانی ایمیل',
                'verbose_name_plural': 'تنظیمات اطلاع\u200cرسانی ایمیل',
                'ordering': ['-created_at'],
            },
        ),
    ]
