# Generated by Django 4.2.16 on 2025-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_email_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تراکنش درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'پرداخت دستی'), ('gateway', 'درگاه پرداخت')], default='manual', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
    ]
