# Generated by Django 4.2.16 on 2025-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0030_payment_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='plan_type',
            field=models.CharField(choices=[('fat_burning', 'چربی سوزی'), ('bulk', 'حجم'), ('hypertrophy', 'هایپروتروفی'), ('corrective', 'اصلاحی')], default='hypertrophy', max_length=20, verbose_name='نوع برنامه'),
        ),
    ]
