# Generated by Django 5.2.1 on 2025-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0032_remove_workout_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='equipment_access',
            field=models.CharField(blank=True, choices=[('full_gym', 'الف) باشگاه بدنسازی با تجهیزات کامل (همه چی هست، فقط بگو چی کار کنم!)'), ('home_gym', 'ب) باشگاه خانگی با تجهیزات محدود (دمبل، کش، میله بارفیکس و…)'), ('bodyweight', 'ج) فقط وزن بدن (هیچی ندارم، فقط خودمم و اراده\u200cام!)'), ('outdoor', 'د) فضای باز (پارک، فضای سبز و…)')], max_length=20, null=True, verbose_name='به چه تجهیزاتی دسترسی دارید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='injury_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات آسیب\u200cدیدگی (در صورت وجود)'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='injury_history',
            field=models.CharField(blank=True, choices=[('has_injury', 'الف) بله، سابقه\u200cی آسیب\u200cدیدگی در (لطفاً ذکر کنید کجای بدنتون و نوع آسیب رو) دارم و/یا در (لطفاً ذکر کنید کجای بدنتون) درد مزمن دارم.'), ('no_injury', 'ب) خیر، خدا رو شکر هیچ آسیب\u200cدیدگی خاصی ندارم و دردی هم احساس نمی\u200cکنم.')], max_length=20, null=True, verbose_name='آیا سابقه\u200cی آسیب\u200cدیدگی خاصی دارید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('early_morning', 'الف) صبح زود (انگار انرژی روزم از همینجا تامین میشه!)'), ('midday', 'ب) اواسط روز (همون تایم ناهار یا یه استراحت کوتاه.)'), ('evening', 'ج) عصر (بعد از کار یا دانشگاه، انرژی\u200cام رو می\u200cذارم برای باشگاه.)'), ('night', 'د) شب (دنیای خوابالوها رو بیخیال، من زنده\u200cام!)'), ('flexible', 'ه) هر زمانی که بشه! (برام فرقی نداره، فقط برنامه\u200cاش رو بگید!)')], max_length=20, null=True, verbose_name='معمولاً چه ساعاتی از روز برای تمرین راحت\u200cترید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='session_duration',
            field=models.CharField(blank=True, choices=[('under_45', 'الف) کمتر از 45 دقیقه (فقط می\u200cخوام یه کوچولو فعال باشم.)'), ('45_60', 'ب) 45-60 دقیقه (مثل برنامه\u200cی قبلیم، عالیه!)'), ('60_90', 'ج) 60-90 دقیقه (من وقت\u200cگذارم و می\u200cتونم حسابی وقت بذارم.)'), ('over_90', 'د) بیشتر از 90 دقیقه (می\u200cخوام سنگ تموم بذارم!)')], max_length=20, null=True, verbose_name='چقدر زمان برای هر جلسه تمرینی؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='training_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'الف) مبتدی (کمتر از 6 ماه)'), ('intermediate', 'ب) متوسط (6 ماه تا 2 سال)'), ('advanced', 'ج) پیشرفته (بیشتر از 2 سال)')], max_length=20, null=True, verbose_name='سابقه\u200cی تمرینی شما چقدره؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='training_frequency',
            field=models.CharField(blank=True, choices=[('2_3_days', 'الف) 2-3 روز (تازه شروع کردم و می\u200cخوام آروم آروم پیش برم.)'), ('3_4_days', 'ب) 3-4 روز (برنامه تمرینی قبلیم هم همین تعداد بود و بدنم عادت داره.)'), ('4_5_days', 'ج) 4-5 روز (عاشق تمرینم و هر روز باشگاه پاتوقمه!)'), ('6_7_days', 'د) 6-7 روز (من مگه زندگی هم دارم؟! فقط باشگاه!)')], max_length=20, null=True, verbose_name='در هفته چند روز می\u200cتونید تمرین کنید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='training_goal',
            field=models.CharField(blank=True, choices=[('muscle_gain', 'الف) افزایش حجم و قدرت عضلانی (می\u200cخوام بترکونم و هر چی دمبله جابجا کنم!)'), ('weight_loss', 'ب) کاهش وزن و چربی\u200cسوزی (می\u200cخوام مثل شناگر المپیک، بدون چربی باشم!)'), ('endurance', 'ج) افزایش استقامت و آمادگی جسمانی (می\u200cخوام تو ماراتن شرکت کنم و نفسم نگیره!)'), ('general_health', 'د) بهبود سلامت عمومی و تناسب اندام (فقط می\u200cخوام سرحال باشم و از زندگی لذت ببرم!)'), ('sexual_health', 'ه) تقویت قوای جنسی و افزایش تستوسترون (هدف اصلی که قبلاً صحبت کردیم، هر روز آماده\u200cی آماده باشم!)')], max_length=20, null=True, verbose_name='هدف اصلی\u200cتون از تمرین کردن چیه؟'),
        ),
    ]
