# Generated by Django 5.2.1 on 2025-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0033_planrequest_equipment_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='allergy_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات آلرژی یا محدودیت\u200cهای غذایی'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='chronic_disease_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات بیماری خاص و محدودیت\u200cها'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='chronic_disease_history',
            field=models.CharField(blank=True, choices=[('has_diet_restriction', 'الف) بله، سابقه بیماری (لطفاً ذکر کنید) را دارم و باید (مثلاً: نمک کم بخورم، قند کنترل کنم، گلوتن نخورم و…)'), ('has_no_diet_restriction', 'ب) بله، سابقه بیماری (لطفاً ذکر کنید) را دارم، اما پزشک رژیم غذایی خاصی توصیه نکرده است.'), ('no_chronic_disease', 'ج) خیر، خوشبختانه هیچ سابقه بیماری خاصی ندارم.'), ('unknown_history', 'د) از سابقه بیماری خاصی اطلاع ندارم و تا به حال آزمایشات مربوطه را انجام نداده\u200cام.')], max_length=30, null=True, verbose_name='سابقه بیماری خاص'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='cooking_time',
            field=models.CharField(blank=True, choices=[('plenty_time', 'الف) وقت و حوصله کافی برای آشپزی روزانه دارم. (آشپزی برام تفریحه!)'), ('quick_easy', 'ب) ترجیح می\u200cدهم غذاهای سریع و آسان آماده کنم. (وقت ندارم، باید زود برم سراغ بقیه\u200cی کارام!)'), ('moderate_time', 'ج) حاضرم برای آماده\u200cسازی غذاهای سالم، کمی وقت بگذارم. (بینابین!)')], max_length=20, null=True, verbose_name='چقدر زمان و حوصله برای آشپزی دارید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='daily_activity',
            field=models.CharField(blank=True, choices=[('very_low', 'الف) بسیار کم (بیشتر پشت میز نشینم یا کارم بی\u200cحرکته.)'), ('low', 'ب) کم (حرکت معمولی دارم، مثلاً پیاده\u200cروی کوتاه یا کارهای سبک خونه.)'), ('moderate', 'ج) متوسط (کارهای روزمره\u200cام شامل تحرک نسبی میشه، مثلاً زیاد راه می\u200cرم.)'), ('high', 'د) زیاد (کارم فیزیکیه یا در طول روز خیلی فعالیت دارم.)')], max_length=20, null=True, verbose_name='میزان فعالیت بدنی روزانه\u200cتون چقدره؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='diet_goal',
            field=models.CharField(blank=True, choices=[('protein_lover', 'الف) عاشق گوشت و پروتئینم (مرغ، ماهی، گوشت قرمز… هرچی پروتئینه!)'), ('plant_based', 'ب) بیشتر گیاه\u200cخوارم یا به غذاهای گیاهی علاقه دارم (حبوبات، سبزیجات، غلات…)'), ('omnivore', 'ج) همه\u200cچی\u200cخوارم و با بیشتر غذاها مشکلی ندارم.'), ('food_dislikes', 'د) از (لطفاً ذکر کنید) متنفرم و نمی\u200cتونم بخورم. (مثلاً: بادمجان، کلم بروکلی، شیر…)')], max_length=20, null=True, verbose_name='هدف اصلی شما از برنامه\u200cی غذایی چیه؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('has_allergy', 'الف) بله، به (لطفاً ذکر کنید) آلرژی دارم/عدم تحمل دارم. (مثلاً: گلوتن، لاکتوز، آجیل…)'), ('medical_restriction', 'ب) بله، پزشکم توصیه کرده از (لطفاً ذکر کنید) پرهیز کنم.'), ('no_restrictions', 'ج) خیر، هیچ محدودیت غذایی خاصی ندارم.')], max_length=30, null=True, verbose_name='آیا محدودیت غذایی خاصی دارید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='food_dislikes_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات غذاهای غیرقابل تحمل'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='food_type_preference',
            field=models.CharField(blank=True, choices=[('home_cooked', 'الف) بیشتر غذاهای خانگی و تازه.'), ('mixed', 'ب) ترکیب غذاهای خانگی و آماده/رستورانی (برای راحتی).'), ('ready_made', 'ج) بیشتر غذاهای آماده و رستورانی (به دلیل مشغله کاری یا عدم تمایل به آشپزی).')], max_length=20, null=True, verbose_name='ترجیح نوع خوراکی\u200cها'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='meal_frequency',
            field=models.CharField(blank=True, choices=[('3_main_meals', 'الف) 3 وعده\u200cی اصلی (صبحانه، ناهار، شام)'), ('3_plus_1_2_snacks', 'ب) 3 وعده\u200cی اصلی و 1-2 میان\u200cوعده'), ('3_plus_3_snacks', 'ج) 3 وعده\u200cی اصلی و 3+ میان\u200cوعده'), ('irregular', 'د) نامنظم (گاهی 2 وعده، گاهی بیشتر…)')], max_length=20, null=True, verbose_name='در حال حاضر چند وعده غذایی می\u200cخورید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='medical_condition_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات بیماری یا داروهای مصرفی'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='medical_conditions',
            field=models.CharField(blank=True, choices=[('has_condition_meds', 'الف) بله، (لطفاً ذکر کنید) دارم و (لطفاً ذکر کنید) دارو مصرف می\u200cکنم.'), ('has_condition_no_meds', 'ب) بله، بیماری خاصی دارم اما داروی خاصی مصرف نمی\u200cکنم.'), ('no_conditions', 'ج) خیر، هیچ بیماری خاصی ندارم و داروی خاصی هم مصرف نمی\u200cکنم.')], max_length=30, null=True, verbose_name='آیا بیماری یا داروی خاصی دارید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='supplement_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات مکمل\u200cهای مصرفی'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='supplement_use',
            field=models.CharField(blank=True, choices=[('currently_using', 'الف) بله، در حال حاضر از (لطفاً ذکر کنید) استفاده می\u200cکنم.'), ('planning_to_use', 'ب) بله، قصد دارم از (لطفاً ذکر کنید) استفاده کنم.'), ('not_using', 'ج) خیر، در حال حاضر هیچ مکملی مصرف نمی\u200cکنم و قصد هم ندارم.'), ('need_guidance', 'د) نیاز به راهنمایی دارم که چه مکمل\u200cهایی برای اهدافم مناسبند.')], max_length=20, null=True, verbose_name='آیا از مکمل\u200cهای غذایی استفاده می\u200cکنید؟'),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='water_intake',
            field=models.CharField(blank=True, choices=[('high', 'الف) بله، روزانه حداقل 8 لیوان یا بیشتر.'), ('moderate', 'ب) متوسط، حدود 4-7 لیوان در روز.'), ('low', 'ج) کم، کمتر از 4 لیوان در روز.'), ('forget', 'د) فراموش می\u200cکنم یا اصلاً تشنه نمی\u200cشم.')], max_length=20, null=True, verbose_name='آب کافی در طول روز می\u200cنوشید؟'),
        ),
    ]
