# Generated by Django 5.2.1 on 2025-08-20 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0034_planrequest_allergy_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InBodyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ آزمایش اینبادی')),
                ('image', models.ImageField(upload_to='inbody_reports/', verbose_name='تصویر آزمایش اینبادی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ مربی')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbody_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش اینبادی',
                'verbose_name_plural': 'گزارش\u200cهای اینبادی',
                'ordering': ['-report_date'],
            },
        ),
    ]
