# Generated by Django 5.2.1 on 2025-08-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0035_inbodyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
