# Generated by Django 5.2.1 on 2025-08-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0036_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام بانک'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='iban',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا'),
        ),
    ]
