# Generated by Django 5.2.1 on 2025-09-02 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0037_paymentcard_account_number_paymentcard_bank_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='مدت (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی شهریه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای شهریه',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='TuitionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='tuition_receipts/', verbose_name='تصویر رسید')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداخت شده (تومان)')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_receipts', to=settings.AUTH_USER_MODEL, verbose_name='ورزشکار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.tuitioncategory', verbose_name='دسته\u200cبندی شهریه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tuitions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط')),
            ],
            options={
                'verbose_name': 'رسید شهریه',
                'verbose_name_plural': 'رسیدهای شهریه',
                'ordering': ['-created_at'],
            },
        ),
    ]
