# Generated by Django 5.2.1 on 2025-09-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0038_tuitioncategory_tuitionreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionreceipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.tuitioncategory', verbose_name='دسته\u200cبندی شهریه'),
        ),
    ]
