# Generated by Django 5.2.1 on 2025-09-25 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0039_make_category_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('monthly', 'ماهانه'), ('seasonal', 'فصلی (3 ماه)'), ('biannual', 'شش\u200cماهه'), ('annual', 'سالانه'), ('custom', 'سفارشی')], default='monthly', max_length=20, verbose_name='نوع شهریه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('valid_from', models.DateField(verbose_name='تاریخ شروع اعتبار')),
                ('valid_until', models.DateField(verbose_name='تاریخ پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_fees', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_fees', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شهریه ویژه',
                'verbose_name_plural': 'شهریه\u200cهای ویژه',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'is_active')},
            },
        ),
    ]
