# Generated by Django 5.2.1 on 2025-09-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0040_add_special_monthly_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شهریه ویژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('paid', 'پرداخت شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_special_fees', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tuition_fees', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شهریه ویژه',
                'verbose_name_plural': 'شهریه\u200cهای ویژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SpecialMonthlyFee',
        ),
    ]
