# Generated by Django 5.2.7 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0043_alter_blogcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinformationuser',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
