# Generated by Django 5.2.7 on 2025-10-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0044_alter_bodyinformationuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
