# Generated by Django 5.2.1 on 2025-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_delete_phoneverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
