# Generated by Django 5.2.1 on 2025-05-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_userprofile_home_address_userprofile_post_code'),
    ]

    operations = [
        # Delete models
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Booklet',
        ),
        migrations.DeleteModel(
            name='BookletPayment',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateComment',
        ),
        
        # Remove fields from UserProfile
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_place',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        
        # Add name field to UserProfile
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
