# Generated by Django 5.2.1 on 2025-05-31 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0013_auto_20250528_2132'),
    ]

    operations = [
        # Body Analysis Report model
        migrations.CreateModel(
            name='BodyAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ آزمایش')),
                ('image', models.ImageField(upload_to='body_analysis/', verbose_name='تصویر آزمایش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ مربی')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_analysis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش آنالیز بدن',
                'verbose_name_plural': 'گزارش‌های آنالیز بدن',
                'ordering': ['-report_date'],
            },
        ),
        
        # Monthly Goal model
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هدف')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='not_started', max_length=15, verbose_name='وضعیت')),
                ('progress', models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name='پیشرفت (درصد)')),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت مربی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هدف ماهانه',
                'verbose_name_plural': 'اهداف ماهانه',
                'ordering': ['-start_date'],
            },
        ),
        
        # Progress Analysis model
        migrations.CreateModel(
            name='ProgressAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('weight', 'وزن'), ('body_fat', 'درصد چربی بدن'), ('muscle_mass', 'توده عضلانی'), ('waist', 'دور کمر'), ('chest', 'دور سینه'), ('arm', 'دور بازو'), ('thigh', 'دور ران'), ('other', 'سایر')], max_length=20, verbose_name='نوع اندازه‌گیری')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مقدار')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='واحد')),
                ('measurement_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ اندازه‌گیری')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آنالیز پیشرفت',
                'verbose_name_plural': 'آنالیزهای پیشرفت',
                'ordering': ['-measurement_date'],
            },
        ),
    ]
