# Generated by Django 5.2.1 on 2025-05-31 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_auto_20250531_1837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'verbose_name': 'برنامه غذایی', 'verbose_name_plural': 'برنامه\u200cهای غذایی'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_date'], 'verbose_name': 'سند', 'verbose_name_plural': 'اسناد'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت پشتیبانی', 'verbose_name_plural': 'تیکت\u200cهای پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='ticketresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ\u200cهای تیکت'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'verbose_name': 'برنامه تمرینی', 'verbose_name_plural': 'برنامه\u200cهای تمرینی'},
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='image',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, verbose_name='مدت (هفته)'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='diet_plans/', verbose_name='فایل برنامه'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('certificate', 'گواهینامه'), ('education', 'مدرک تحصیلی'), ('medical', 'مدارک پزشکی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته')], default='open', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='پاسخ کارمند'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, verbose_name='مدت (هفته)'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='workout_plans/', verbose_name='فایل برنامه'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
